# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GB_iOSFrameworks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GB_iOSFrameworks
  
  pod 'GoogleMaps', '5.2.0'

end
